### ISSUE TITLE
Run Travis only in master/develop branches

### ISSUE THREAD

**Issue by StefanoMagrassi** [contactlab/kubozer#71]
https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

```yaml
# safelist
branches:
  only:
  - master
  - develop
```
